/*-
 * ============LICENSE_START=======================================================
 * ONAP : APP-C
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property.  All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.31 at 10:30:39 AM EDT 
//


package org.openecomp.appc.flow.controller.interfaceData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonRootName;


@XmlAccessorType(XmlAccessType.FIELD)
@JsonRootName(value="input")
@XmlType(name = "input", propOrder = {
    "requestInfo",
    "inventoryInfo",
    "dependencyInfo",
    "tunableParameters",
    "capabilities"
})
@JsonPropertyOrder({"requestInfo",
    "inventoryInfo",
    "dependencyInfo",
    "tunableParameters",
    "capabilities" })
public class Input {

    @XmlElement(name = "request-info")
    @JsonProperty("request-info")
    protected RequestInfo requestInfo;
    @XmlElement(name = "inventory-info")
    @JsonProperty("inventory-info")
    protected InventoryInfo inventoryInfo;
    @XmlElement(name = "dependency-info")
    @JsonProperty("dependency-info")
    protected DependencyInfo dependencyInfo;
    @XmlElement(name = "tunable-parameters")
    @JsonProperty("tunable-parameters")
    protected TunableParameters tunableParameters;
    protected Capabilities capabilities;

    /**
     * Gets the value of the requestInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RequestInfo }
     *     
     */
    public RequestInfo getRequestInfo() {
        return requestInfo;
    }

    /**
     * Sets the value of the requestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestInfo }
     *     
     */
    public void setRequestInfo(RequestInfo value) {
        this.requestInfo = value;
    }

    /**
     * Gets the value of the inventoryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryInfo }
     *     
     */
    public InventoryInfo getInventoryInfo() {
        return inventoryInfo;
    }

    /**
     * Sets the value of the inventoryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryInfo }
     *     
     */
    public void setInventoryInfo(InventoryInfo value) {
        this.inventoryInfo = value;
    }

    /**
     * Gets the value of the dependencyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DependencyInfo }
     *     
     */
    public DependencyInfo getDependencyInfo() {
        return dependencyInfo;
    }

    /**
     * Sets the value of the dependencyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependencyInfo }
     *     
     */
    public void setDependencyInfo(DependencyInfo value) {
        this.dependencyInfo = value;
    }

    /**
     * Gets the value of the tunableParameters property.
     * 
     * @return
     *     possible object is
     *     {@link TunableParameters }
     *     
     */
    public TunableParameters getTunableParameters() {
        return tunableParameters;
    }

    /**
     * Sets the value of the tunableParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link TunableParameters }
     *     
     */
    public void setTunableParameters(TunableParameters value) {
        this.tunableParameters = value;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Capabilities }
     *     
     */
    public Capabilities getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Capabilities }
     *     
     */
    public void setCapabilities(Capabilities value) {
        this.capabilities = value;
    }

    @Override
    public String toString() {
        return "Input [requestInfo=" + requestInfo + ", inventoryInfo="
                + inventoryInfo + ", dependencyInfo=" + dependencyInfo
                + ", tunableParameters=" + tunableParameters
                + ", capabilities=" + capabilities + "]";
    }

}
