/*-
 * ============LICENSE_START=======================================================
 * ONAP : APP-C
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property.  All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.31 at 10:30:39 AM EDT 
//


package org.openecomp.appc.flow.controller.interfaceData;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openecomp.appc.flow.controller.interfaceData package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openecomp.appc.flow.controller.interfaceData
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Capabilities }
     * 
     */
    public Capabilities createCapabilities() {
        return new Capabilities();
    }

    /**
     * Create an instance of {@link RequestInfo }
     * 
     */
    public RequestInfo createRequestInfo() {
        return new RequestInfo();
    }

    /**
     * Create an instance of {@link ActionIdentifier }
     * 
     */
    public ActionIdentifier createActionIdentifier() {
        return new ActionIdentifier();
    }

    /**
     * Create an instance of {@link DependencyInfo }
     * 
     */
    public DependencyInfo createDependencyInfo() {
        return new DependencyInfo();
    }

    /**
     * Create an instance of {@link Vnfcs }
     * 
     */
    public Vnfcs createVnfcs() {
        return new Vnfcs();
    }

    /**
     * Create an instance of {@link Vm }
     * 
     */
    public Vm createVm() {
        return new Vm();
    }

    /**
     * Create an instance of {@link Vnfcslist }
     * 
     */
    public Vnfcslist createVnfcslist() {
        return new Vnfcslist();
    }

    /**
     * Create an instance of {@link TunableParameters }
     * 
     */
    public TunableParameters createTunableParameters() {
        return new TunableParameters();
    }

    /**
     * Create an instance of {@link VnfInfo }
     * 
     */
    public VnfInfo createVnfInfo() {
        return new VnfInfo();
    }

    /**
     * Create an instance of {@link InventoryInfo }
     * 
     */
    public InventoryInfo createInventoryInfo() {
        return new InventoryInfo();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

}
