/*-
 * ============LICENSE_START=======================================================
 * ONAP : APP-C
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property.  All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.31 at 10:30:39 AM EDT 
//


package org.openecomp.appc.flow.controller.interfaceData;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vnfcType",
    "mandatory",
    "resilience",
    "parents"
})
@XmlRootElement(name = "vnfcs")
@JsonRootName(value="vnfcs")
public class Vnfcs {

    @XmlElement(name = "vnfc-type", required = true)
    @JsonProperty("vnfc-type")
    protected String vnfcType;
    @XmlElement(required = true)
    @JsonProperty("mandatory")
    protected String mandatory;
    @XmlElement(required = true)
    @JsonProperty("resilience")
    protected String resilience;
    @XmlList
    @XmlElement(required = true)
    @JsonProperty("parents")
    protected List<String> parents;

    /**
     * Gets the value of the vnfcType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfcType() {
        return vnfcType;
    }

    /**
     * Sets the value of the vnfcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfcType(String value) {
        this.vnfcType = value;
    }

    /**
     * Gets the value of the mandatory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMandatory() {
        return mandatory;
    }

    /**
     * Sets the value of the mandatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMandatory(String value) {
        this.mandatory = value;
    }

    /**
     * Gets the value of the resilience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResilience() {
        return resilience;
    }

    /**
     * Sets the value of the resilience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResilience(String value) {
        this.resilience = value;
    }

    /**
     * Gets the value of the parents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getParents() {
        if (parents == null) {
            parents = new ArrayList<String>();
        }
        return this.parents;
    }

    @Override
    public String toString() {
        return "Vnfcs [vnfcType=" + vnfcType + ", mandatory=" + mandatory
                + ", resilience=" + resilience + ", parents=" + parents + "]";
    }

}
