/*-
 * ============LICENSE_START=======================================================
 * ONAP : APP-C
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property.  All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.31 at 10:30:39 AM EDT 
//


package org.openecomp.appc.flow.controller.interfaceData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for vnfcslist complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vnfcslist">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vnfc-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vnfc-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vnfcslist", propOrder = {
    "vnfcType",
    "vnfcName"
})
public class Vnfcslist {

    @XmlElement(name = "vnfc-type", required = true)
    @JsonProperty("vnfc-type")
    protected String vnfcType;
    @XmlElement(name = "vnfc-name", required = true)
    @JsonProperty("vnfc-name")
    protected String vnfcName;

    /**
     * Gets the value of the vnfcType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfcType() {
        return vnfcType;
    }

    /**
     * Sets the value of the vnfcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfcType(String value) {
        this.vnfcType = value;
    }

    /**
     * Gets the value of the vnfcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVnfcName() {
        return vnfcName;
    }

    /**
     * Sets the value of the vnfcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVnfcName(String value) {
        this.vnfcName = value;
    }

    @Override
    public String toString() {
        return "Vnfcslist [vnfcType=" + vnfcType + ", vnfcName=" + vnfcName
                + "]";
    }

}
